stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/Nifty_50_1y_dataset.csv
    outs:
      - data/processed\kmeans_ready.csv
      - models/scaler.pkl